# Generated by Django 4.1.3 on 2023-01-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_app', '0003_remove_order_user_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
